http:
  ip: 127.0.0.1
  port: 8550
  indexPageNames: ["index.html", "index.htm", "default.html", "default.htm"]

http:
  fileService:
    mapping: "/"
    url: ""
    suffixes: [""]
    staticMapping: true
    contentDisposition: true
    nodyTemplateDirectory: "path"
    directoryHandled: true


# TODO: 这个文件最后要加载到软件里面，提供默认配置方式，而不是在文件中 设置默认值。