INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/asio.hpp \
    $$PWD/asio/any_completion_executor.hpp \
    $$PWD/asio/any_completion_handler.hpp \
    $$PWD/asio/any_io_executor.hpp \
    $$PWD/asio/append.hpp \
    $$PWD/asio/as_tuple.hpp \
    $$PWD/asio/associated_allocator.hpp \
    $$PWD/asio/associated_cancellation_slot.hpp \
    $$PWD/asio/associated_executor.hpp \
    $$PWD/asio/associated_immediate_executor.hpp \
    $$PWD/asio/associator.hpp \
    $$PWD/asio/async_result.hpp \
    $$PWD/asio/awaitable.hpp \
    $$PWD/asio/basic_datagram_socket.hpp \
    $$PWD/asio/basic_deadline_timer.hpp \
    $$PWD/asio/basic_file.hpp \
    $$PWD/asio/basic_io_object.hpp \
    $$PWD/asio/basic_random_access_file.hpp \
    $$PWD/asio/basic_raw_socket.hpp \
    $$PWD/asio/basic_readable_pipe.hpp \
    $$PWD/asio/basic_seq_packet_socket.hpp \
    $$PWD/asio/basic_serial_port.hpp \
    $$PWD/asio/basic_signal_set.hpp \
    $$PWD/asio/basic_socket.hpp \
    $$PWD/asio/basic_socket_acceptor.hpp \
    $$PWD/asio/basic_socket_iostream.hpp \
    $$PWD/asio/basic_socket_streambuf.hpp \
    $$PWD/asio/basic_stream_file.hpp \
    $$PWD/asio/basic_stream_socket.hpp \
    $$PWD/asio/basic_streambuf.hpp \
    $$PWD/asio/basic_streambuf_fwd.hpp \
    $$PWD/asio/basic_waitable_timer.hpp \
    $$PWD/asio/basic_writable_pipe.hpp \
    $$PWD/asio/bind_allocator.hpp \
    $$PWD/asio/bind_cancellation_slot.hpp \
    $$PWD/asio/bind_executor.hpp \
    $$PWD/asio/bind_immediate_executor.hpp \
    $$PWD/asio/buffer.hpp \
    $$PWD/asio/buffer_registration.hpp \
    $$PWD/asio/buffered_read_stream.hpp \
    $$PWD/asio/buffered_read_stream_fwd.hpp \
    $$PWD/asio/buffered_stream.hpp \
    $$PWD/asio/buffered_stream_fwd.hpp \
    $$PWD/asio/buffered_write_stream.hpp \
    $$PWD/asio/buffered_write_stream_fwd.hpp \
    $$PWD/asio/buffers_iterator.hpp \
    $$PWD/asio/cancellation_signal.hpp \
    $$PWD/asio/cancellation_state.hpp \
    $$PWD/asio/cancellation_type.hpp \
    $$PWD/asio/co_spawn.hpp \
    $$PWD/asio/completion_condition.hpp \
    $$PWD/asio/compose.hpp \
    $$PWD/asio/connect.hpp \
    $$PWD/asio/connect_pipe.hpp \
    $$PWD/asio/consign.hpp \
    $$PWD/asio/coroutine.hpp \
    $$PWD/asio/deadline_timer.hpp \
    $$PWD/asio/defer.hpp \
    $$PWD/asio/deferred.hpp \
    $$PWD/asio/detached.hpp \
    $$PWD/asio/detail/array.hpp \
    $$PWD/asio/detail/array_fwd.hpp \
    $$PWD/asio/detail/assert.hpp \
    $$PWD/asio/detail/atomic_count.hpp \
    $$PWD/asio/detail/base_from_cancellation_state.hpp \
    $$PWD/asio/detail/base_from_completion_cond.hpp \
    $$PWD/asio/detail/bind_handler.hpp \
    $$PWD/asio/detail/blocking_executor_op.hpp \
    $$PWD/asio/detail/buffer_resize_guard.hpp \
    $$PWD/asio/detail/buffer_sequence_adapter.hpp \
    $$PWD/asio/detail/buffered_stream_storage.hpp \
    $$PWD/asio/detail/call_stack.hpp \
    $$PWD/asio/detail/chrono.hpp \
    $$PWD/asio/detail/chrono_time_traits.hpp \
    $$PWD/asio/detail/completion_handler.hpp \
    $$PWD/asio/detail/composed_work.hpp \
    $$PWD/asio/detail/concurrency_hint.hpp \
    $$PWD/asio/detail/conditionally_enabled_event.hpp \
    $$PWD/asio/detail/conditionally_enabled_mutex.hpp \
    $$PWD/asio/detail/config.hpp \
    $$PWD/asio/detail/consuming_buffers.hpp \
    $$PWD/asio/detail/cstddef.hpp \
    $$PWD/asio/detail/cstdint.hpp \
    $$PWD/asio/detail/date_time_fwd.hpp \
    $$PWD/asio/detail/deadline_timer_service.hpp \
    $$PWD/asio/detail/dependent_type.hpp \
    $$PWD/asio/detail/descriptor_ops.hpp \
    $$PWD/asio/detail/descriptor_read_op.hpp \
    $$PWD/asio/detail/descriptor_write_op.hpp \
    $$PWD/asio/detail/dev_poll_reactor.hpp \
    $$PWD/asio/detail/epoll_reactor.hpp \
    $$PWD/asio/detail/event.hpp \
    $$PWD/asio/detail/eventfd_select_interrupter.hpp \
    $$PWD/asio/detail/exception.hpp \
    $$PWD/asio/detail/executor_function.hpp \
    $$PWD/asio/detail/executor_op.hpp \
    $$PWD/asio/detail/fd_set_adapter.hpp \
    $$PWD/asio/detail/fenced_block.hpp \
    $$PWD/asio/detail/functional.hpp \
    $$PWD/asio/detail/future.hpp \
    $$PWD/asio/detail/global.hpp \
    $$PWD/asio/detail/handler_alloc_helpers.hpp \
    $$PWD/asio/detail/handler_cont_helpers.hpp \
    $$PWD/asio/detail/handler_tracking.hpp \
    $$PWD/asio/detail/handler_type_requirements.hpp \
    $$PWD/asio/detail/handler_work.hpp \
    $$PWD/asio/detail/hash_map.hpp \
    $$PWD/asio/detail/impl/buffer_sequence_adapter.ipp \
    $$PWD/asio/detail/impl/descriptor_ops.ipp \
    $$PWD/asio/detail/impl/dev_poll_reactor.hpp \
    $$PWD/asio/detail/impl/dev_poll_reactor.ipp \
    $$PWD/asio/detail/impl/epoll_reactor.hpp \
    $$PWD/asio/detail/impl/epoll_reactor.ipp \
    $$PWD/asio/detail/impl/eventfd_select_interrupter.ipp \
    $$PWD/asio/detail/impl/handler_tracking.ipp \
    $$PWD/asio/detail/impl/io_uring_descriptor_service.ipp \
    $$PWD/asio/detail/impl/io_uring_file_service.ipp \
    $$PWD/asio/detail/impl/io_uring_service.hpp \
    $$PWD/asio/detail/impl/io_uring_service.ipp \
    $$PWD/asio/detail/impl/io_uring_socket_service_base.ipp \
    $$PWD/asio/detail/impl/kqueue_reactor.hpp \
    $$PWD/asio/detail/impl/kqueue_reactor.ipp \
    $$PWD/asio/detail/impl/null_event.ipp \
    $$PWD/asio/detail/impl/pipe_select_interrupter.ipp \
    $$PWD/asio/detail/impl/posix_event.ipp \
    $$PWD/asio/detail/impl/posix_mutex.ipp \
    $$PWD/asio/detail/impl/posix_serial_port_service.ipp \
    $$PWD/asio/detail/impl/posix_thread.ipp \
    $$PWD/asio/detail/impl/posix_tss_ptr.ipp \
    $$PWD/asio/detail/impl/reactive_descriptor_service.ipp \
    $$PWD/asio/detail/impl/reactive_socket_service_base.ipp \
    $$PWD/asio/detail/impl/resolver_service_base.ipp \
    $$PWD/asio/detail/impl/scheduler.ipp \
    $$PWD/asio/detail/impl/select_reactor.hpp \
    $$PWD/asio/detail/impl/select_reactor.ipp \
    $$PWD/asio/detail/impl/service_registry.hpp \
    $$PWD/asio/detail/impl/service_registry.ipp \
    $$PWD/asio/detail/impl/signal_set_service.ipp \
    $$PWD/asio/detail/impl/socket_ops.ipp \
    $$PWD/asio/detail/impl/socket_select_interrupter.ipp \
    $$PWD/asio/detail/impl/strand_executor_service.hpp \
    $$PWD/asio/detail/impl/strand_executor_service.ipp \
    $$PWD/asio/detail/impl/strand_service.hpp \
    $$PWD/asio/detail/impl/strand_service.ipp \
    $$PWD/asio/detail/impl/thread_context.ipp \
    $$PWD/asio/detail/impl/throw_error.ipp \
    $$PWD/asio/detail/impl/timer_queue_ptime.ipp \
    $$PWD/asio/detail/impl/timer_queue_set.ipp \
    $$PWD/asio/detail/impl/win_event.ipp \
    $$PWD/asio/detail/impl/win_iocp_file_service.ipp \
    $$PWD/asio/detail/impl/win_iocp_handle_service.ipp \
    $$PWD/asio/detail/impl/win_iocp_io_context.hpp \
    $$PWD/asio/detail/impl/win_iocp_io_context.ipp \
    $$PWD/asio/detail/impl/win_iocp_serial_port_service.ipp \
    $$PWD/asio/detail/impl/win_iocp_socket_service_base.ipp \
    $$PWD/asio/detail/impl/win_mutex.ipp \
    $$PWD/asio/detail/impl/win_object_handle_service.ipp \
    $$PWD/asio/detail/impl/win_static_mutex.ipp \
    $$PWD/asio/detail/impl/win_thread.ipp \
    $$PWD/asio/detail/impl/win_tss_ptr.ipp \
    $$PWD/asio/detail/impl/winrt_ssocket_service_base.ipp \
    $$PWD/asio/detail/impl/winrt_timer_scheduler.hpp \
    $$PWD/asio/detail/impl/winrt_timer_scheduler.ipp \
    $$PWD/asio/detail/impl/winsock_init.ipp \
    $$PWD/asio/detail/initiate_defer.hpp \
    $$PWD/asio/detail/initiate_dispatch.hpp \
    $$PWD/asio/detail/initiate_post.hpp \
    $$PWD/asio/detail/io_control.hpp \
    $$PWD/asio/detail/io_object_impl.hpp \
    $$PWD/asio/detail/io_uring_descriptor_read_at_op.hpp \
    $$PWD/asio/detail/io_uring_descriptor_read_op.hpp \
    $$PWD/asio/detail/io_uring_descriptor_service.hpp \
    $$PWD/asio/detail/io_uring_descriptor_write_at_op.hpp \
    $$PWD/asio/detail/io_uring_descriptor_write_op.hpp \
    $$PWD/asio/detail/io_uring_file_service.hpp \
    $$PWD/asio/detail/io_uring_null_buffers_op.hpp \
    $$PWD/asio/detail/io_uring_operation.hpp \
    $$PWD/asio/detail/io_uring_service.hpp \
    $$PWD/asio/detail/io_uring_socket_accept_op.hpp \
    $$PWD/asio/detail/io_uring_socket_connect_op.hpp \
    $$PWD/asio/detail/io_uring_socket_recv_op.hpp \
    $$PWD/asio/detail/io_uring_socket_recvfrom_op.hpp \
    $$PWD/asio/detail/io_uring_socket_recvmsg_op.hpp \
    $$PWD/asio/detail/io_uring_socket_send_op.hpp \
    $$PWD/asio/detail/io_uring_socket_sendto_op.hpp \
    $$PWD/asio/detail/io_uring_socket_service.hpp \
    $$PWD/asio/detail/io_uring_socket_service_base.hpp \
    $$PWD/asio/detail/io_uring_wait_op.hpp \
    $$PWD/asio/detail/is_buffer_sequence.hpp \
    $$PWD/asio/detail/is_executor.hpp \
    $$PWD/asio/detail/keyword_tss_ptr.hpp \
    $$PWD/asio/detail/kqueue_reactor.hpp \
    $$PWD/asio/detail/limits.hpp \
    $$PWD/asio/detail/local_free_on_block_exit.hpp \
    $$PWD/asio/detail/memory.hpp \
    $$PWD/asio/detail/mutex.hpp \
    $$PWD/asio/detail/non_const_lvalue.hpp \
    $$PWD/asio/detail/noncopyable.hpp \
    $$PWD/asio/detail/null_event.hpp \
    $$PWD/asio/detail/null_fenced_block.hpp \
    $$PWD/asio/detail/null_global.hpp \
    $$PWD/asio/detail/null_mutex.hpp \
    $$PWD/asio/detail/null_reactor.hpp \
    $$PWD/asio/detail/null_signal_blocker.hpp \
    $$PWD/asio/detail/null_socket_service.hpp \
    $$PWD/asio/detail/null_static_mutex.hpp \
    $$PWD/asio/detail/null_thread.hpp \
    $$PWD/asio/detail/null_tss_ptr.hpp \
    $$PWD/asio/detail/object_pool.hpp \
    $$PWD/asio/detail/old_win_sdk_compat.hpp \
    $$PWD/asio/detail/op_queue.hpp \
    $$PWD/asio/detail/operation.hpp \
    $$PWD/asio/detail/pipe_select_interrupter.hpp \
    $$PWD/asio/detail/pop_options.hpp \
    $$PWD/asio/detail/posix_event.hpp \
    $$PWD/asio/detail/posix_fd_set_adapter.hpp \
    $$PWD/asio/detail/posix_global.hpp \
    $$PWD/asio/detail/posix_mutex.hpp \
    $$PWD/asio/detail/posix_serial_port_service.hpp \
    $$PWD/asio/detail/posix_signal_blocker.hpp \
    $$PWD/asio/detail/posix_static_mutex.hpp \
    $$PWD/asio/detail/posix_thread.hpp \
    $$PWD/asio/detail/posix_tss_ptr.hpp \
    $$PWD/asio/detail/push_options.hpp \
    $$PWD/asio/detail/reactive_descriptor_service.hpp \
    $$PWD/asio/detail/reactive_null_buffers_op.hpp \
    $$PWD/asio/detail/reactive_socket_accept_op.hpp \
    $$PWD/asio/detail/reactive_socket_connect_op.hpp \
    $$PWD/asio/detail/reactive_socket_recv_op.hpp \
    $$PWD/asio/detail/reactive_socket_recvfrom_op.hpp \
    $$PWD/asio/detail/reactive_socket_recvmsg_op.hpp \
    $$PWD/asio/detail/reactive_socket_send_op.hpp \
    $$PWD/asio/detail/reactive_socket_sendto_op.hpp \
    $$PWD/asio/detail/reactive_socket_service.hpp \
    $$PWD/asio/detail/reactive_socket_service_base.hpp \
    $$PWD/asio/detail/reactive_wait_op.hpp \
    $$PWD/asio/detail/reactor.hpp \
    $$PWD/asio/detail/reactor_op.hpp \
    $$PWD/asio/detail/reactor_op_queue.hpp \
    $$PWD/asio/detail/recycling_allocator.hpp \
    $$PWD/asio/detail/regex_fwd.hpp \
    $$PWD/asio/detail/resolve_endpoint_op.hpp \
    $$PWD/asio/detail/resolve_op.hpp \
    $$PWD/asio/detail/resolve_query_op.hpp \
    $$PWD/asio/detail/resolver_service.hpp \
    $$PWD/asio/detail/resolver_service_base.hpp \
    $$PWD/asio/detail/scheduler.hpp \
    $$PWD/asio/detail/scheduler_operation.hpp \
    $$PWD/asio/detail/scheduler_task.hpp \
    $$PWD/asio/detail/scheduler_thread_info.hpp \
    $$PWD/asio/detail/scoped_lock.hpp \
    $$PWD/asio/detail/scoped_ptr.hpp \
    $$PWD/asio/detail/select_interrupter.hpp \
    $$PWD/asio/detail/select_reactor.hpp \
    $$PWD/asio/detail/service_registry.hpp \
    $$PWD/asio/detail/signal_blocker.hpp \
    $$PWD/asio/detail/signal_handler.hpp \
    $$PWD/asio/detail/signal_init.hpp \
    $$PWD/asio/detail/signal_op.hpp \
    $$PWD/asio/detail/signal_set_service.hpp \
    $$PWD/asio/detail/socket_holder.hpp \
    $$PWD/asio/detail/socket_ops.hpp \
    $$PWD/asio/detail/socket_option.hpp \
    $$PWD/asio/detail/socket_select_interrupter.hpp \
    $$PWD/asio/detail/socket_types.hpp \
    $$PWD/asio/detail/source_location.hpp \
    $$PWD/asio/detail/static_mutex.hpp \
    $$PWD/asio/detail/std_event.hpp \
    $$PWD/asio/detail/std_fenced_block.hpp \
    $$PWD/asio/detail/std_global.hpp \
    $$PWD/asio/detail/std_mutex.hpp \
    $$PWD/asio/detail/std_static_mutex.hpp \
    $$PWD/asio/detail/std_thread.hpp \
    $$PWD/asio/detail/strand_executor_service.hpp \
    $$PWD/asio/detail/strand_service.hpp \
    $$PWD/asio/detail/string_view.hpp \
    $$PWD/asio/detail/thread.hpp \
    $$PWD/asio/detail/thread_context.hpp \
    $$PWD/asio/detail/thread_group.hpp \
    $$PWD/asio/detail/thread_info_base.hpp \
    $$PWD/asio/detail/throw_error.hpp \
    $$PWD/asio/detail/throw_exception.hpp \
    $$PWD/asio/detail/timer_queue.hpp \
    $$PWD/asio/detail/timer_queue_base.hpp \
    $$PWD/asio/detail/timer_queue_ptime.hpp \
    $$PWD/asio/detail/timer_queue_set.hpp \
    $$PWD/asio/detail/timer_scheduler.hpp \
    $$PWD/asio/detail/timer_scheduler_fwd.hpp \
    $$PWD/asio/detail/tss_ptr.hpp \
    $$PWD/asio/detail/type_traits.hpp \
    $$PWD/asio/detail/utility.hpp \
    $$PWD/asio/detail/wait_handler.hpp \
    $$PWD/asio/detail/wait_op.hpp \
    $$PWD/asio/detail/win_event.hpp \
    $$PWD/asio/detail/win_fd_set_adapter.hpp \
    $$PWD/asio/detail/win_global.hpp \
    $$PWD/asio/detail/win_iocp_file_service.hpp \
    $$PWD/asio/detail/win_iocp_handle_read_op.hpp \
    $$PWD/asio/detail/win_iocp_handle_service.hpp \
    $$PWD/asio/detail/win_iocp_handle_write_op.hpp \
    $$PWD/asio/detail/win_iocp_io_context.hpp \
    $$PWD/asio/detail/win_iocp_null_buffers_op.hpp \
    $$PWD/asio/detail/win_iocp_operation.hpp \
    $$PWD/asio/detail/win_iocp_overlapped_op.hpp \
    $$PWD/asio/detail/win_iocp_overlapped_ptr.hpp \
    $$PWD/asio/detail/win_iocp_serial_port_service.hpp \
    $$PWD/asio/detail/win_iocp_socket_accept_op.hpp \
    $$PWD/asio/detail/win_iocp_socket_connect_op.hpp \
    $$PWD/asio/detail/win_iocp_socket_recv_op.hpp \
    $$PWD/asio/detail/win_iocp_socket_recvfrom_op.hpp \
    $$PWD/asio/detail/win_iocp_socket_recvmsg_op.hpp \
    $$PWD/asio/detail/win_iocp_socket_send_op.hpp \
    $$PWD/asio/detail/win_iocp_socket_service.hpp \
    $$PWD/asio/detail/win_iocp_socket_service_base.hpp \
    $$PWD/asio/detail/win_iocp_thread_info.hpp \
    $$PWD/asio/detail/win_iocp_wait_op.hpp \
    $$PWD/asio/detail/win_mutex.hpp \
    $$PWD/asio/detail/win_object_handle_service.hpp \
    $$PWD/asio/detail/win_static_mutex.hpp \
    $$PWD/asio/detail/win_thread.hpp \
    $$PWD/asio/detail/win_tss_ptr.hpp \
    $$PWD/asio/detail/winapp_thread.hpp \
    $$PWD/asio/detail/wince_thread.hpp \
    $$PWD/asio/detail/winrt_async_manager.hpp \
    $$PWD/asio/detail/winrt_async_op.hpp \
    $$PWD/asio/detail/winrt_resolve_op.hpp \
    $$PWD/asio/detail/winrt_resolver_service.hpp \
    $$PWD/asio/detail/winrt_socket_connect_op.hpp \
    $$PWD/asio/detail/winrt_socket_recv_op.hpp \
    $$PWD/asio/detail/winrt_socket_send_op.hpp \
    $$PWD/asio/detail/winrt_ssocket_service.hpp \
    $$PWD/asio/detail/winrt_ssocket_service_base.hpp \
    $$PWD/asio/detail/winrt_timer_scheduler.hpp \
    $$PWD/asio/detail/winrt_utils.hpp \
    $$PWD/asio/detail/winsock_init.hpp \
    $$PWD/asio/detail/work_dispatcher.hpp \
    $$PWD/asio/detail/wrapped_handler.hpp \
    $$PWD/asio/dispatch.hpp \
    $$PWD/asio/error.hpp \
    $$PWD/asio/error_code.hpp \
    $$PWD/asio/execution.hpp \
    $$PWD/asio/execution/allocator.hpp \
    $$PWD/asio/execution/any_executor.hpp \
    $$PWD/asio/execution/bad_executor.hpp \
    $$PWD/asio/execution/blocking.hpp \
    $$PWD/asio/execution/blocking_adaptation.hpp \
    $$PWD/asio/execution/context.hpp \
    $$PWD/asio/execution/context_as.hpp \
    $$PWD/asio/execution/executor.hpp \
    $$PWD/asio/execution/impl/bad_executor.ipp \
    $$PWD/asio/execution/invocable_archetype.hpp \
    $$PWD/asio/execution/mapping.hpp \
    $$PWD/asio/execution/occupancy.hpp \
    $$PWD/asio/execution/outstanding_work.hpp \
    $$PWD/asio/execution/prefer_only.hpp \
    $$PWD/asio/execution/relationship.hpp \
    $$PWD/asio/execution_context.hpp \
    $$PWD/asio/executor.hpp \
    $$PWD/asio/executor_work_guard.hpp \
    $$PWD/asio/experimental/append.hpp \
    $$PWD/asio/experimental/as_single.hpp \
    $$PWD/asio/experimental/as_tuple.hpp \
    $$PWD/asio/experimental/awaitable_operators.hpp \
    $$PWD/asio/experimental/basic_channel.hpp \
    $$PWD/asio/experimental/basic_concurrent_channel.hpp \
    $$PWD/asio/experimental/cancellation_condition.hpp \
    $$PWD/asio/experimental/channel.hpp \
    $$PWD/asio/experimental/channel_error.hpp \
    $$PWD/asio/experimental/channel_traits.hpp \
    $$PWD/asio/experimental/co_composed.hpp \
    $$PWD/asio/experimental/co_spawn.hpp \
    $$PWD/asio/experimental/concurrent_channel.hpp \
    $$PWD/asio/experimental/coro.hpp \
    $$PWD/asio/experimental/coro_traits.hpp \
    $$PWD/asio/experimental/deferred.hpp \
    $$PWD/asio/experimental/detail/channel_handler.hpp \
    $$PWD/asio/experimental/detail/channel_message.hpp \
    $$PWD/asio/experimental/detail/channel_operation.hpp \
    $$PWD/asio/experimental/detail/channel_payload.hpp \
    $$PWD/asio/experimental/detail/channel_receive_op.hpp \
    $$PWD/asio/experimental/detail/channel_send_functions.hpp \
    $$PWD/asio/experimental/detail/channel_send_op.hpp \
    $$PWD/asio/experimental/detail/channel_service.hpp \
    $$PWD/asio/experimental/detail/coro_completion_handler.hpp \
    $$PWD/asio/experimental/detail/coro_promise_allocator.hpp \
    $$PWD/asio/experimental/detail/has_signature.hpp \
    $$PWD/asio/experimental/detail/impl/channel_service.hpp \
    $$PWD/asio/experimental/detail/partial_promise.hpp \
    $$PWD/asio/experimental/impl/as_single.hpp \
    $$PWD/asio/experimental/impl/channel_error.ipp \
    $$PWD/asio/experimental/impl/co_composed.hpp \
    $$PWD/asio/experimental/impl/coro.hpp \
    $$PWD/asio/experimental/impl/parallel_group.hpp \
    $$PWD/asio/experimental/impl/promise.hpp \
    $$PWD/asio/experimental/impl/use_coro.hpp \
    $$PWD/asio/experimental/impl/use_promise.hpp \
    $$PWD/asio/experimental/parallel_group.hpp \
    $$PWD/asio/experimental/prepend.hpp \
    $$PWD/asio/experimental/promise.hpp \
    $$PWD/asio/experimental/use_coro.hpp \
    $$PWD/asio/experimental/use_promise.hpp \
    $$PWD/asio/file_base.hpp \
    $$PWD/asio/generic/basic_endpoint.hpp \
    $$PWD/asio/generic/datagram_protocol.hpp \
    $$PWD/asio/generic/detail/endpoint.hpp \
    $$PWD/asio/generic/detail/impl/endpoint.ipp \
    $$PWD/asio/generic/raw_protocol.hpp \
    $$PWD/asio/generic/seq_packet_protocol.hpp \
    $$PWD/asio/generic/stream_protocol.hpp \
    $$PWD/asio/handler_continuation_hook.hpp \
    $$PWD/asio/high_resolution_timer.hpp \
    $$PWD/asio/impl/any_completion_executor.ipp \
    $$PWD/asio/impl/any_io_executor.ipp \
    $$PWD/asio/impl/append.hpp \
    $$PWD/asio/impl/as_tuple.hpp \
    $$PWD/asio/impl/awaitable.hpp \
    $$PWD/asio/impl/buffered_read_stream.hpp \
    $$PWD/asio/impl/buffered_write_stream.hpp \
    $$PWD/asio/impl/cancellation_signal.ipp \
    $$PWD/asio/impl/co_spawn.hpp \
    $$PWD/asio/impl/connect.hpp \
    $$PWD/asio/impl/connect_pipe.hpp \
    $$PWD/asio/impl/connect_pipe.ipp \
    $$PWD/asio/impl/consign.hpp \
    $$PWD/asio/impl/deferred.hpp \
    $$PWD/asio/impl/detached.hpp \
    $$PWD/asio/impl/error.ipp \
    $$PWD/asio/impl/error_code.ipp \
    $$PWD/asio/impl/execution_context.hpp \
    $$PWD/asio/impl/execution_context.ipp \
    $$PWD/asio/impl/executor.hpp \
    $$PWD/asio/impl/executor.ipp \
    $$PWD/asio/impl/io_context.hpp \
    $$PWD/asio/impl/io_context.ipp \
    $$PWD/asio/impl/multiple_exceptions.ipp \
    $$PWD/asio/impl/prepend.hpp \
    $$PWD/asio/impl/read.hpp \
    $$PWD/asio/impl/read_at.hpp \
    $$PWD/asio/impl/read_until.hpp \
    $$PWD/asio/impl/redirect_error.hpp \
    $$PWD/asio/impl/serial_port_base.hpp \
    $$PWD/asio/impl/serial_port_base.ipp \
    $$PWD/asio/impl/spawn.hpp \
    $$PWD/asio/impl/src.hpp \
    $$PWD/asio/impl/system_context.hpp \
    $$PWD/asio/impl/system_context.ipp \
    $$PWD/asio/impl/system_executor.hpp \
    $$PWD/asio/impl/thread_pool.hpp \
    $$PWD/asio/impl/thread_pool.ipp \
    $$PWD/asio/impl/use_awaitable.hpp \
    $$PWD/asio/impl/use_future.hpp \
    $$PWD/asio/impl/write.hpp \
    $$PWD/asio/impl/write_at.hpp \
    $$PWD/asio/io_context.hpp \
    $$PWD/asio/io_context_strand.hpp \
    $$PWD/asio/io_service.hpp \
    $$PWD/asio/io_service_strand.hpp \
    $$PWD/asio/ip/address.hpp \
    $$PWD/asio/ip/address_v4.hpp \
    $$PWD/asio/ip/address_v4_iterator.hpp \
    $$PWD/asio/ip/address_v4_range.hpp \
    $$PWD/asio/ip/address_v6.hpp \
    $$PWD/asio/ip/address_v6_iterator.hpp \
    $$PWD/asio/ip/address_v6_range.hpp \
    $$PWD/asio/ip/bad_address_cast.hpp \
    $$PWD/asio/ip/basic_endpoint.hpp \
    $$PWD/asio/ip/basic_resolver.hpp \
    $$PWD/asio/ip/basic_resolver_entry.hpp \
    $$PWD/asio/ip/basic_resolver_iterator.hpp \
    $$PWD/asio/ip/basic_resolver_query.hpp \
    $$PWD/asio/ip/basic_resolver_results.hpp \
    $$PWD/asio/ip/detail/endpoint.hpp \
    $$PWD/asio/ip/detail/impl/endpoint.ipp \
    $$PWD/asio/ip/detail/socket_option.hpp \
    $$PWD/asio/ip/host_name.hpp \
    $$PWD/asio/ip/icmp.hpp \
    $$PWD/asio/ip/impl/address.hpp \
    $$PWD/asio/ip/impl/address.ipp \
    $$PWD/asio/ip/impl/address_v4.hpp \
    $$PWD/asio/ip/impl/address_v4.ipp \
    $$PWD/asio/ip/impl/address_v6.hpp \
    $$PWD/asio/ip/impl/address_v6.ipp \
    $$PWD/asio/ip/impl/basic_endpoint.hpp \
    $$PWD/asio/ip/impl/host_name.ipp \
    $$PWD/asio/ip/impl/network_v4.hpp \
    $$PWD/asio/ip/impl/network_v4.ipp \
    $$PWD/asio/ip/impl/network_v6.hpp \
    $$PWD/asio/ip/impl/network_v6.ipp \
    $$PWD/asio/ip/multicast.hpp \
    $$PWD/asio/ip/network_v4.hpp \
    $$PWD/asio/ip/network_v6.hpp \
    $$PWD/asio/ip/resolver_base.hpp \
    $$PWD/asio/ip/resolver_query_base.hpp \
    $$PWD/asio/ip/tcp.hpp \
    $$PWD/asio/ip/udp.hpp \
    $$PWD/asio/ip/unicast.hpp \
    $$PWD/asio/ip/v6_only.hpp \
    $$PWD/asio/is_applicable_property.hpp \
    $$PWD/asio/is_contiguous_iterator.hpp \
    $$PWD/asio/is_executor.hpp \
    $$PWD/asio/is_read_buffered.hpp \
    $$PWD/asio/is_write_buffered.hpp \
    $$PWD/asio/local/basic_endpoint.hpp \
    $$PWD/asio/local/connect_pair.hpp \
    $$PWD/asio/local/datagram_protocol.hpp \
    $$PWD/asio/local/detail/endpoint.hpp \
    $$PWD/asio/local/detail/impl/endpoint.ipp \
    $$PWD/asio/local/seq_packet_protocol.hpp \
    $$PWD/asio/local/stream_protocol.hpp \
    $$PWD/asio/multiple_exceptions.hpp \
    $$PWD/asio/packaged_task.hpp \
    $$PWD/asio/placeholders.hpp \
    $$PWD/asio/posix/basic_descriptor.hpp \
    $$PWD/asio/posix/basic_stream_descriptor.hpp \
    $$PWD/asio/posix/descriptor.hpp \
    $$PWD/asio/posix/descriptor_base.hpp \
    $$PWD/asio/posix/stream_descriptor.hpp \
    $$PWD/asio/post.hpp \
    $$PWD/asio/prefer.hpp \
    $$PWD/asio/prepend.hpp \
    $$PWD/asio/query.hpp \
    $$PWD/asio/random_access_file.hpp \
    $$PWD/asio/read.hpp \
    $$PWD/asio/read_at.hpp \
    $$PWD/asio/read_until.hpp \
    $$PWD/asio/readable_pipe.hpp \
    $$PWD/asio/recycling_allocator.hpp \
    $$PWD/asio/redirect_error.hpp \
    $$PWD/asio/registered_buffer.hpp \
    $$PWD/asio/require.hpp \
    $$PWD/asio/require_concept.hpp \
    $$PWD/asio/serial_port.hpp \
    $$PWD/asio/serial_port_base.hpp \
    $$PWD/asio/signal_set.hpp \
    $$PWD/asio/signal_set_base.hpp \
    $$PWD/asio/socket_base.hpp \
    $$PWD/asio/spawn.hpp \
    $$PWD/asio/ssl.hpp \
    $$PWD/asio/ssl/context.hpp \
    $$PWD/asio/ssl/context_base.hpp \
    $$PWD/asio/ssl/detail/buffered_handshake_op.hpp \
    $$PWD/asio/ssl/detail/engine.hpp \
    $$PWD/asio/ssl/detail/handshake_op.hpp \
    $$PWD/asio/ssl/detail/impl/engine.ipp \
    $$PWD/asio/ssl/detail/impl/openssl_init.ipp \
    $$PWD/asio/ssl/detail/io.hpp \
    $$PWD/asio/ssl/detail/openssl_init.hpp \
    $$PWD/asio/ssl/detail/openssl_types.hpp \
    $$PWD/asio/ssl/detail/password_callback.hpp \
    $$PWD/asio/ssl/detail/read_op.hpp \
    $$PWD/asio/ssl/detail/shutdown_op.hpp \
    $$PWD/asio/ssl/detail/stream_core.hpp \
    $$PWD/asio/ssl/detail/verify_callback.hpp \
    $$PWD/asio/ssl/detail/write_op.hpp \
    $$PWD/asio/ssl/error.hpp \
    $$PWD/asio/ssl/host_name_verification.hpp \
    $$PWD/asio/ssl/impl/context.hpp \
    $$PWD/asio/ssl/impl/context.ipp \
    $$PWD/asio/ssl/impl/error.ipp \
    $$PWD/asio/ssl/impl/host_name_verification.ipp \
    $$PWD/asio/ssl/impl/rfc2818_verification.ipp \
    $$PWD/asio/ssl/impl/src.hpp \
    $$PWD/asio/ssl/rfc2818_verification.hpp \
    $$PWD/asio/ssl/stream.hpp \
    $$PWD/asio/ssl/stream_base.hpp \
    $$PWD/asio/ssl/verify_context.hpp \
    $$PWD/asio/ssl/verify_mode.hpp \
    $$PWD/asio/static_thread_pool.hpp \
    $$PWD/asio/steady_timer.hpp \
    $$PWD/asio/strand.hpp \
    $$PWD/asio/stream_file.hpp \
    $$PWD/asio/streambuf.hpp \
    $$PWD/asio/system_context.hpp \
    $$PWD/asio/system_error.hpp \
    $$PWD/asio/system_executor.hpp \
    $$PWD/asio/system_timer.hpp \
    $$PWD/asio/this_coro.hpp \
    $$PWD/asio/thread.hpp \
    $$PWD/asio/thread_pool.hpp \
    $$PWD/asio/time_traits.hpp \
    $$PWD/asio/traits/equality_comparable.hpp \
    $$PWD/asio/traits/execute_member.hpp \
    $$PWD/asio/traits/prefer_free.hpp \
    $$PWD/asio/traits/prefer_member.hpp \
    $$PWD/asio/traits/query_free.hpp \
    $$PWD/asio/traits/query_member.hpp \
    $$PWD/asio/traits/query_static_constexpr_member.hpp \
    $$PWD/asio/traits/require_concept_free.hpp \
    $$PWD/asio/traits/require_concept_member.hpp \
    $$PWD/asio/traits/require_free.hpp \
    $$PWD/asio/traits/require_member.hpp \
    $$PWD/asio/traits/static_query.hpp \
    $$PWD/asio/traits/static_require.hpp \
    $$PWD/asio/traits/static_require_concept.hpp \
    $$PWD/asio/ts/buffer.hpp \
    $$PWD/asio/ts/executor.hpp \
    $$PWD/asio/ts/internet.hpp \
    $$PWD/asio/ts/io_context.hpp \
    $$PWD/asio/ts/net.hpp \
    $$PWD/asio/ts/netfwd.hpp \
    $$PWD/asio/ts/socket.hpp \
    $$PWD/asio/ts/timer.hpp \
    $$PWD/asio/unyield.hpp \
    $$PWD/asio/use_awaitable.hpp \
    $$PWD/asio/use_future.hpp \
    $$PWD/asio/uses_executor.hpp \
    $$PWD/asio/version.hpp \
    $$PWD/asio/wait_traits.hpp \
    $$PWD/asio/windows/basic_object_handle.hpp \
    $$PWD/asio/windows/basic_overlapped_handle.hpp \
    $$PWD/asio/windows/basic_random_access_handle.hpp \
    $$PWD/asio/windows/basic_stream_handle.hpp \
    $$PWD/asio/windows/object_handle.hpp \
    $$PWD/asio/windows/overlapped_handle.hpp \
    $$PWD/asio/windows/overlapped_ptr.hpp \
    $$PWD/asio/windows/random_access_handle.hpp \
    $$PWD/asio/windows/stream_handle.hpp \
    $$PWD/asio/writable_pipe.hpp \
    $$PWD/asio/write.hpp \
    $$PWD/asio/write_at.hpp \
    $$PWD/asio/yield.hpp
